### ISSUE TITLE
Execute a workflow with HCC1395 exome data through the Strelka variant caller.

### ISSUE THREAD

**Issue by jasonwalker80** [genome/arvados_trial#10]

**Comment by jasonwalker80** [comment]
This depends on #4 #14 and #17

**Comment by tmooney** [comment]
Current status: The [Arvados CWL docs](http://doc.arvados.org/user/cwl/cwl-runner.html) say to check this before running a workflow:
```
tmooney@shell:~$ docker version
Client:
 Version:      1.9.1
 API version:  1.21
 Go version:   go1.4.3
 Git commit:   a34a1d5
 Built:        Fri Nov 20 17:56:04 UTC 2015
 OS/Arch:      linux/amd64
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
```
It's returning an error... so Docker's not available to try the workflow.  Not sure if that's intentional or a misconfiguration in the setup of the machine.

**Comment by tmooney** [comment]
Now have `docker` access.  The workflow ran and statuses were updated in the web interface as one might expect!  The workflow failed, so next step will be to look into why...

**Comment by tmooney** [comment]
I tried running the bwa-mem example and got the same error:
```
8/10/2016 5:28:05 PM 	compute2 	1 	task-print 	0 	ERROR:root:Unhandled exception
8/10/2016 5:28:05 PM 	compute2 	1 	task-print 	0 	Traceback (most recent call last):
8/10/2016 5:28:05 PM 	compute2 	1 	task-print 	0 	File "/tmp/crunch-job/src/crunch_scripts/cwl-runner", line 55, in <module>
8/10/2016 5:28:05 PM 	compute2 	1 	task-print 	0 	t = load_tool(job_order_object, runner.arvMakeTool)
8/10/2016 5:28:05 PM 	compute2 	1 	task-print 	0 	File "/usr/lib/python2.7/dist-packages/cwltool/load_tool.py", line 149, in load_tool
8/10/2016 5:28:05 PM 	compute2 	1 	task-print 	0 	strict=strict)
8/10/2016 5:28:05 PM 	compute2 	1 	task-print 	0 	File "/usr/lib/python2.7/dist-packages/cwltool/load_tool.py", line 77, in validate_document
8/10/2016 5:28:05 PM 	compute2 	1 	task-print 	0 	process.get_schema(workflowobj["cwlVersion"])[:2]
8/10/2016 5:28:05 PM 	compute2 	1 	task-print 	0 	File "/usr/lib/python2.7/dist-packages/cwltool/process.py", line 107, in get_schema
8/10/2016 5:28:05 PM 	compute2 	1 	task-print 	0 	"https://w3id.org/cwl/CommonWorkflowLanguage.yml", cache=cache)
8/10/2016 5:28:05 PM 	compute2 	1 	task-print 	0 	File "/usr/lib/python2.7/dist-packages/schema_salad/schema.py", line 166, in load_schema
8/10/2016 5:28:05 PM 	compute2 	1 	task-print 	0 	schema_doc, schema_metadata = metaschema_loader.resolve_ref(schema_ref, "")
8/10/2016 5:28:05 PM 	compute2 	1 	task-print 	0 	File "/usr/lib/python2.7/dist-packages/schema_salad/ref_resolver.py", line 294, in resolve_ref
8/10/2016 5:28:05 PM 	compute2 	1 	task-print 	0 	doc = self.fetch(doc_url)
8/10/2016 5:28:05 PM 	compute2 	1 	task-print 	0 	File "/usr/lib/python2.7/dist-packages/schema_salad/ref_resolver.py", line 497, in fetch
8/10/2016 5:28:05 PM 	compute2 	1 	task-print 	0 	text = self.fetch_text(url)
8/10/2016 5:28:05 PM 	compute2 	1 	task-print 	0 	File "/usr/lib/python2.7/dist-packages/schema_salad/ref_resolver.py", line 478, in fetch_text
8/10/2016 5:28:05 PM 	compute2 	1 	task-print 	0 	raise RuntimeError(url, e)
8/10/2016 5:28:05 PM 	compute2 	1 	task-print 	0 	RuntimeError: ('https://w3id.org/cwl/CommonWorkflowLanguage.yml', ConnectionError(ProtocolError('Connection aborted.', gaierror(-2, 'Name or service not known')),))
```

**Comment by jasonwalker80** [comment]
I would suggest submitting the error to `support@curoverse.com`.

**Comment by tmooney** [comment]
E-mail is sent.

**Comment by tmooney** [comment]
This one ran through!  I've shared the [result directory](https://cloud.curoverse.com/collections/download/qr1hi-4zz18-2o2j5opdbc3ret0/2bpeit1rztwqx0dfexlxrzd451ujesbe4bvqxpnjr3y3gapzx6/).  Closing this issue.
