### ISSUE TITLE
get_chromosome_list failure in toil_compatibility branch

### ISSUE THREAD

**Issue by jasonwalker80** [genome/arvados_trial#110]
The most worrisome error to me looks like:
bash: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory

I'm not sure how this would have succeeded before unless the Docker image changes (installing R) somehow removed a library/dependency?

The full TOIL error:

blade8-3-12.gsc.wustl.edu 2017-03-24 10:09:49,857 MainThread WARNING toil.leader: The job seems to have left a log file, indicating failure: 'file:///gscmnt/gc2764/cad/jwalker/toil_test/arvados_trial/pindel/get_chromosome_list.cwl' bash -c /bin/grep -v '^@' $1 | /usr/bin/cut -f 1 | /usr/bin/sort | /usr/bin/uniq -- L/z/jobk8JVde
---TOIL WORKER OUTPUT LOG---
L/z/jobk8JVde    INFO:toil:Running Toil version 3.6.0-f930a841e79d1032a44670b85c319411ca539ede.
L/z/jobk8JVde    [job get_chromosome_list.cwl] /gscmnt/gc2764/cad/jwalker/toil_test/full_exome/tmpArXRsN$ bash \
L/z/jobk8JVde        -c \
L/z/jobk8JVde        '/bin/grep -v '"'"'^@'"'"' $1 | /usr/bin/cut -f 1 | /usr/bin/sort | /usr/bin/uniq' \
L/z/jobk8JVde        -- \
L/z/jobk8JVde        /gscmnt/gc2764/cad/jwalker/toil_test/full_exome/tmpwp5jAM/stg9e48aa17-a0d9-4f58-b079-d613cbddb7ca/xgen-exome-research-panel-targets.interval_list > /gscmnt/gc2764/cad/jwalker/toil_test/full_exome/tmpArXRsN/chromosome.list
L/z/jobk8JVde    INFO:cwltool:[job get_chromosome_list.cwl] /gscmnt/gc2764/cad/jwalker/toil_test/full_exome/tmpArXRsN$ bash \
L/z/jobk8JVde        -c \
L/z/jobk8JVde        '/bin/grep -v '"'"'^@'"'"' $1 | /usr/bin/cut -f 1 | /usr/bin/sort | /usr/bin/uniq' \
L/z/jobk8JVde        -- \
L/z/jobk8JVde        /gscmnt/gc2764/cad/jwalker/toil_test/full_exome/tmpwp5jAM/stg9e48aa17-a0d9-4f58-b079-d613cbddb7ca/xgen-exome-research-panel-targets.interval_list > /gscmnt/gc2764/cad/jwalker/toil_test/full_exome/tmpArXRsN/chromosome.list
L/z/jobk8JVde    bash: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
L/z/jobk8JVde    [job get_chromosome_list.cwl] completed permanentFail
L/z/jobk8JVde    WARNING:cwltool:[job get_chromosome_list.cwl] completed permanentFail
L/z/jobk8JVde    Final process status is permanentFail
L/z/jobk8JVde    WARNING:cwltool:Final process status is permanentFail
L/z/jobk8JVde    Traceback (most recent call last):
L/z/jobk8JVde      File "/usr/local/lib/python2.7/dist-packages/toil/worker.py", line 340, in main
L/z/jobk8JVde        job._runner(jobGraph=jobGraph, jobStore=jobStore, fileStore=fileStore)
L/z/jobk8JVde      File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1271, in _runner
L/z/jobk8JVde        returnValues = self._run(jobGraph, fileStore)
L/z/jobk8JVde      File "/usr/local/lib/python2.7/dist-packages/toil/job.py", line 1218, in _run
L/z/jobk8JVde        return self.run(fileStore)
L/z/jobk8JVde      File "/usr/local/lib/python2.7/dist-packages/toil/cwl/cwltoil.py", line 286, in run
L/z/jobk8JVde        **opts)
L/z/jobk8JVde      File "/usr/local/lib/python2.7/dist-packages/cwltool/main.py", line 240, in single_job_executor
L/z/jobk8JVde        raise WorkflowException(u"Process status is %s" % (final_status))
L/z/jobk8JVde    WorkflowException: Process status is ['permanentFail']
L/z/jobk8JVde    ERROR:toil.worker:Exiting the worker because of a failed job on host blade14-4-4.gsc.wustl.edu

**Comment by jasonwalker80** [comment]
There was a missing library in the docker-cle image.
